name: StepRunner

#Triger / Kapan Action-nya jalan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  AutomationStep:

    runs-on: ubuntu-latest

    steps:
    
    #Download Code dari Repo
    - uses: actions/checkout@v4
    
    #Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    #install Browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.3

    #Setup Gradlew
    - name: Setup Gradlew
      run: chmod +x gradlew 
    
    #run test
    - name: run test
      run: ./gradlew cucumber

    #hasil Test-Result
    - name: Archive Report
      uses: actions/upload-artifact@v4.3.0
      if: success() #always() # success() , failure(), canceled()
      with: 
          Name: JUnit4 Reports
          path: reports/StepDefinitionReport.html
